config/routes.rb
Mtghub::Application.routes.draw do
  get 'register' => 'users#new', as: :register

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :mtg_sets
    end
  end

  resources :users do
    resources :decks do
      get 'comments'
    end
  end

  resources :decks do
    resources :suggestions
    resources :comments, only: :create
    resources :stars
    resources :stats
  end

  resources :suggestions do
    resources :comments, only: :create
  end

  resources :comments

  resources :mtg_sets
  resources :cards
  resources :forks

  delete 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'users#new'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :forks, class_name: 'Deck', foreign_key: 'origin_id'
  belongs_to :origin, class_name: 'Deck'
  has_many :cards_decks
  has_many :cards, through: :cards_decks, dependent: :destroy
  has_one :sideboard, dependent: :destroy
  has_many :suggestions, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :stars, dependent: :destroy

  validates :title, presence: true

  before_create :create_sideboard

  scope :for_format, lambda { |x| order('stars_count desc').
    where(format: x).where(['updated_at > ?', 2.months.ago]).limit(5) }

  def sideboard_cards
    sideboard ? sideboard.cards : create_sideboard.cards
  end

  def sideboard_cards= cards
    create_sideboard if !sideboard
    sideboard.cards = cards
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :require_user, only: [:create, :destroy]

  def index
    @deck = Deck
  end

  def new
    @deck = current_user.decks.new
  end

  def edit
    @mtg_sets = MtgSet.all
    @deck = current_user.decks.find_by_id(params[:id]).decorate
  end

  def create
    @deck = current_user.decks.build deck_params
    if @deck.save
      redirect_to edit_user_deck_url current_user, @deck
    else
      render :new
    end
  end

  def destroy
    @deck = current_user.decks.find_by_id params[:id]
    @deck.destroy
    redirect_to current_user
  end

  def show
    @deck = Deck.find_by_id(params[:id]).decorate
  end

  def comments
    @deck = Deck.find_by_id(params[:deck_id]).decorate
  end

private
  def deck_params
    params.require(:deck).permit(:title, :format, :tags, :colors)
  end

  def user
    @user ||= User.find_by_id params[:user_id]
  end
end

app/views/decks/_deck.slim
.deck-view.span12
  .cards
    h3
      ' Cards
      span.count= @deck.non_lands.count
    - @deck.mana_groups.each_pair do |cmc, cards|
      .span2.mana-cost class=cmc
        - cards.each do |card|
          = render card
  .lands
    br
    h3
      ' Lands
      span.count= @deck.lands.count
    - @deck.land_groups.each do |lands|
      .span2.mana-cost
        -lands.each do |land|
          = render land

  .sideboard
    br
    h3
      ' Sideboard
      span.count= @deck.sideboard_cards.count
    - @deck.sideboard_groups.each do |cards|
      .span2.mana-cost
        - cards.each do |card|
          = render card

app/views/decks/_form.slim
= simple_form_for [current_user, @deck] do |f|
  = f.input :title
  = f.input :format, as: :select, collection: Format.titles
  = f.input :tags
  = f.button :submit

app/views/decks/_links.slim
.row-fluid.deck-header
  h4.pull-left.deck-title
    = link_to @deck.user.username, @deck.user
    '  /
    = link_to @deck.title, [@deck.user, @deck]
    '
  .pagination.pull-right.deck-settings
    ul
      = @deck.stars_link
      = @deck.suggest
      = @deck.fork
      = @deck.edit

.navbar.deck-nav
  .navbar-inner
    .container
      ul.nav
        li.deck= link_to 'Deck', [@deck.user, @deck]
        li.stats= link_to 'Stats', deck_stats_url(@deck)
        li.suggestions
          = link_to deck_suggestions_url(@deck) do
            ' Suggestions
            code= @deck.suggestions.open.count
        li.comments
          = link_to user_deck_comments_url(@deck.user, @deck) do
            ' Comments
            code= @deck.comments.count
        li.stars= link_to 'Stars', deck_stars_url(@deck)

javascript:
  $(".deck-nav ul.nav .#{active}").addClass('active');

app/views/decks/_mtg_blocks.slim
.row-fluid
  .span12
    .card-search
      = text_field_tag :card_search
      .results
    .row-fluid
      .mtg_block.span6
        ul.hint
          li Click adds to deck
          li Alt-click adds to sideboard
          li Click to remove card from deck
        ul.nav.nav-tabs.nav-stacked.block-list
          - @mtg_sets.each do |set|
            li= link_to set.title, set, remote: true
      .mtg_set.span6

app/views/decks/comments.slim
= render 'links', active: :comments
.comments
  - @deck.comments.each do |comment|
    = render comment
= render 'comments/form', commentable: @deck

app/views/decks/edit.slim
.row-fluid
  .span12
    .row-fluid
      .span4
        .card-preview
        = render 'mtg_blocks'
      .span8
        h4.pull-left= @deck.title
        = link_to @deck, method: :delete, data: { confirm: 'Are you sure?' } do
          .btn.btn-danger.pull-right.deck-save
            i.icon-trash
        = link_to [@deck.user, @deck] do
          .btn.btn-info.pull-right.deck-save Save
        .deck.deck-data data-url="#{cards_url}" data-deck=@deck.id
          = render @deck

app/views/decks/index.slim
.decks
  - Format.titles.each do |format|
    .deck-box.span5
      h4= format
      hr
      table.table.table-striped
        - @deck.for_format(format).each do |deck|
          tr
            td
              = link_to deck.title, [deck.user, deck]
            td
              i.icon-star
              '
              = deck.stars_count
            td.right
              = image_tag deck.user.gravatar_url size: 16, default: 'identicon'
              '
              = link_to deck.user.username, deck.user

app/views/decks/new.slim
.span4.offset4
  = render 'form'

app/views/decks/show.slim
.deck
  = render 'links', active: :deck
  = render @deck